general:
    no-matches: "§cThere are no lobbies or matches available.\n\nRejoin later!"
    main-message-prefix: "§l»§r "

maps:
    map-dir: "maps"
    map-file: "Map.class"
    world-prefix: "match-"

lobby:
    default-lobby-map: "Lobby"
    join-strategy: "SMALLEST"
    chat-format: "%s §7§l»§r %s"
    auto-start: true
    minimum-players: 2
    maximum-players: 24
    start-countdown:
        message: "§eThe lobby will end in §6%s §esecond(s)."
        time: 20

match:
    join-strategy: "SMALLEST"
    start-countdown:
        message: "§eThe games will begin in §6%s §esecond(s)."
        time: 20
    feast:
        time: 300
        rarity-increase: 0.15
        message: "§3There has been a feast!"

    death-player-message: "§c%0$s §7was slain by §c%1$c§7."
    death-other-message: "§c%0$s §7mysteriously died."
    player-remain-message: "§6%0$d §7players remain"
    end-message-list:
    - "§5 # # # # # # # # # # # #"
    - "§5# # §6   Game Over!   §5  # #"
    - "§5# # %s wins! # #"
    - "§5 # # # # # # # # # # # #"

thirst:
    health-damage: 1
    hunger-damage: 0

chat:
    radius: 30

scoreboard:
    time-string: "§6§lTime"
    kills-string: "§4§lKills"
    alive-string: "§2§lAlive"
    sanity-string: "§5§lSanity"
    thirst-string: "§7§lThirst"
